#ifndef SX_GLOBAL_SYMBOLS_H
#define SX_GLOBAL_SYMBOLS_H

enum
{
  _FIRST_ELEMENT_      = 10000,

  // Globals
  IDS_PLUGIN_NAME,
  IDS_PLUGIN_VERSION,
  IDS_PLUGIN_DESCRIPTION,

  // Status
  IDS_PROCESSING_FILE,
  IDS_PROCESSING_WORLD,
  IDS_OF,
  IDS_BUILDING_POLY,

  // MainUI
  DLG_MAINUI,
  IDC_BROWSE_BIG,
  IDC_BROWSE_SMALL,
  IDC_IMPORT,
  IDC_PLANE_SEARCH_EPSILON,
  IDS_BAD_MAP_FILE,
  IDS_LOAD_FILE_TITLE,
  IDS_FILE_LOAD_ERROR,

  _DUMMY_ELEMENT_
};

#endif